const state={metrics:{active:null,attention:null,done:null},systems:[['Vercel / ЦУП','ok','Защищён и доступен'],['GitHub / код','ok','Синхронизация включена'],['n8n','wait','Ждёт телеметрию'],['Linux / AI Commander','wait','Ждёт телеметрию'],['Росток / публикации','wait','Ждёт телеметрию'],['Telegram / MAX','wait','Ждёт телеметрию']],projects:[['Точка притяжения','Основной управленческий контур'],['Горизонт 45 / Асгард','Девелопмент и территория'],['Медиа / AI','Монтаж, студия, автоматизация'],['Центр сообществ','Заявки и взаимодействия'],['Киноуроки','Методика, фильмы, медиа'],['РЭО Крым','Экологические проекты'],['РКО','Русское космическое общество'],['О будущем','Отдельный проект участия'],['Личный контур','Обучение и эксперименты']],events:[['Сейчас','ЦУП переведён в защищённый production-контур','ok'],['Сейчас','GitHub → Vercel автодеплой работает','ok'],['Следующий шаг','Подключение телеметрии n8n/Linux/ботов','wait']],inbox:[['Telegram / MAX','Источник будет подключён через защищённый ingest API','wait'],['Центр сообществ','Очередь заявок готовится к подключению','wait'],['Документы','Реестр и статусы синхронизации будут подключены','wait']]};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function render(){ const focus=$('#focusList');if(focus){const rows=[];if(state.metrics.attention!=null)rows.push(['attention',state.metrics.attention+' требуют решения']);if(state.metrics.active!=null)rows.push(['active',state.metrics.active+' активных процессов']);const issues=state.systems.filter(x=>x[1]!=='ok').slice(0,3);issues.forEach(x=>rows.push([x[1],x[0]+' · '+x[2]]));focus.innerHTML=(rows.length?rows:[['wait','Подключаем реальные данные штаба']]).map(x=>`<div class="focus-row"><span class="dot ${x[0]==='attention'?'err':x[0]==='active'?'ok':x[0]}"></span><b>${x[1]}</b></div>`).join('');} $('#m-active').textContent=state.metrics.active??'—';$('#m-attn').textContent=state.metrics.attention??'—';$('#m-done').textContent=state.metrics.done??'—';$('#systems').innerHTML=state.systems.map(x=>`<div class="sys"><span class="dot ${x[1]}"></span><div><b>${x[0]}</b><small>${x[2]}</small></div></div>`).join('');$('#events').innerHTML=state.events.map(x=>`<div class="event"><time>${x[0]}</time><span class="dot ${x[2]}"></span><p>${x[1]}</p></div>`).join('');$('#projectList').innerHTML=state.projects.map((x,i)=>`<article><span>${String(i+1).padStart(2,'0')}</span><div><b>${x[0]}</b><small>${x[1]}</small></div><i>›</i></article>`).join('');$('#inboxList').innerHTML=state.inbox.map(x=>`<div class="event"><time>${x[0]}</time><span class="dot ${x[2]}"></span><p>${x[1]}</p></div>`).join('');$('#flowList').innerHTML=state.systems.slice(2).map(x=>`<div class="event"><time>${x[0]}</time><span class="dot ${x[1]}"></span><p>${x[2]}</p></div>`).join('');$('#healthText').textContent='ONLINE';$('#updated').textContent='production';}
$$('nav button').forEach(b=>b.onclick=()=>{$$('nav button').forEach(x=>x.classList.toggle('active',x===b));$$('.view').forEach(v=>v.classList.toggle('active',v.id===b.dataset.view));scrollTo({top:0,behavior:'smooth'});});
setInterval(()=>$('#clock').textContent=new Date().toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'}),1000);render();
async function refresh(){try{const r=await fetch('/api/state',{cache:'no-store'});if(!r.ok)return;const d=await r.json();Object.assign(state,d);render();$('#updated').textContent='обновлено '+new Date().toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'});}catch(e){}}
refresh();setInterval(refresh,30000);
async function health(){try{const r=await fetch('/api/health',{cache:'no-store'});if(!r.ok)return;const h=await r.json();const msg=h.storageConfigured?'Хранилище подключено':h.ingestConfigured?'Ключ подключён · ждёт хранилище':'Настройка телеметрии';const row=state.systems.find(x=>x[0]==='Vercel / ЦУП');if(row){row[2]='Защищён · '+msg;}render();}catch(e){}}health();setInterval(health,30000);
// MAX Mini App compatibility: safe read-only shell. No write actions are exposed.
(function initMaxMiniApp(){
  document.documentElement.classList.add('readonly-mode');
  const ua=navigator.userAgent||'';
  if(/MAX/i.test(ua)) document.documentElement.classList.add('max-miniapp');
  const bridge=window.WebApp;
  try{bridge?.ready?.();}catch(e){}
})();

(function maxContext(){const w=window.WebApp;if(!w)return;document.documentElement.classList.add('max-mode');document.documentElement.dataset.platform=w.platform||'max';try{w.BackButton?.hide?.();}catch(e){}if(w.getLaunchContext)w.getLaunchContext().then(x=>{document.documentElement.dataset.entry=x?.entryPoint||'default'}).catch(()=>{});})();
